### ISSUE TITLE
Organization page crashes if two of the same agent associations

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#114]
Same agents, same association type.
```
Internal Server Error: /accounting/projects/
Traceback (most recent call last):
  File "/home/ocp/webapp/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ocp/webapp/valuenetwork/valuenetwork/valueaccounting/views.py", line 236, in projects
    association = AgentAssociation.objects.get(is_associate=assoc, has_associate=node, association_type=aat)#
  File "/home/ocp/webapp/env/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ocp/webapp/env/lib/python2.7/site-packages/django/db/models/query.py", line 338, in get
    (self.model._meta.object_name, num)
MultipleObjectsReturned: get() returned more than one AgentAssociation -- it returned 2!
```

**Comment by bhaugen** [comment]
Made the page less fussy. At least does not crash. Next, to prevent duplicate associations...

**Comment by XaviP** [comment]
Closing this issue as commited changes to prod ocp. Please reopen if needed.
