### ISSUE TITLE
Error manage.py migrate with new migrations

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#117]
I realized that in prod ocp there were migrations to apply. When running ./manage.py migrate:
```
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```
Then I runned ./manage.py makemigrations and was added a new one in account app.
There were more migrations not pushed in this app, so I've pushed all:
https://github.com/FreedomCoop/valuenetwork/commit/f587dd7bbc37a9c191f915f516a2835a7f4c7d50
The problem is when I pull from local and make ./manage.py migrate. It seems that trys to apply all migrations, but they are already applied. See error:
```
Running migrations:
  Rendering model states... DONE
  Applying account.0001_initial...Traceback (most recent call last):
  File "./manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/xavi/Documents/freedomcoop/dev/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/xavi/Documents/freedomcoop/dev/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/xavi/Documents/freedomcoop/dev/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/xavi/Documents/freedomcoop/dev/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/xavi/Documents/freedomcoop/dev/env/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/xavi/Documents/freedomcoop/dev/env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/home/xavi/Documents/freedomcoop/dev/env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/xavi/Documents/freedomcoop/dev/env/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/xavi/Documents/freedomcoop/dev/env/local/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/home/xavi/Documents/freedomcoop/dev/env/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 286, in create_model
    self.execute(sql, params or None)
  File "/home/xavi/Documents/freedomcoop/dev/env/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/home/xavi/Documents/freedomcoop/dev/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/xavi/Documents/freedomcoop/dev/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/xavi/Documents/freedomcoop/dev/env/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/xavi/Documents/freedomcoop/dev/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/home/xavi/Documents/freedomcoop/dev/env/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 316, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: table "account_account" already exists
```

**Comment by XaviP** [comment]
There were migrations in prod ocp not pushed, and not necessaries for sqlite dbs. I think the different db, postgres in prod, can be envolved.
To correct it: how can we mark initial migration as done in local dev dbs ??

**Comment by XaviP** [comment]
SOLVED with ./manage.py migrate --fake-initial
It makes initial migration as fake.
Please apply migrations this way in your dev enviroments with last commit.

**Comment by fosterlynn** [comment]
>The problem is when I pull from local and make ./manage.py migrate.

@XaviP just double checking on this statement: You pull from github, not local, correct?

**Comment by XaviP** [comment]
Yes, sorry. Closing.
