### ISSUE TITLE
Error running *python manage.py send_faircoin_requests*

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#159]
```
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ocp/webapp/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/ocp/webapp/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ocp/webapp/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 190, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/ocp/webapp/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named management.commands.send_faircoin_requests
```

**Comment by XaviP** [comment]
Incompatibility with 'work.fobi_form_callbacks'. Now solved.
