### ISSUE TITLE
change_your_project bug

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#183]
Internal Server Error: /work/change-your-project/143/
Traceback (most recent call last):
  File "/home/ocp/webapp/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ocp/webapp/env/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/home/ocp/webapp/env/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ocp/webapp/valuenetwork/work/views.py", line 2074, in change_your_project
    if pro_form.is_valid() and agn_form.is_valid():
UnboundLocalError: local variable 'agn_form' referenced before assignment

**Comment by bum2** [comment]
solved in commit https://github.com/FreedomCoop/valuenetwork/commit/e326b2942bbeb600aa0b9914c8eb1a8a38b774c9
